### ISSUE TITLE
Discord / CKAN

### ISSUE THREAD

**Issue by amoraschi** [rogerwang86/SPOCK#1]
Hi, thank you for making this mod, the Orbiter model is amazing, and congrats on release 0.2.0 💯 

Do you have any plans on creating a Discord for this mod?
And do you have any plans on publishing this on CKAN?

Also, game and CKAN complain about the DepthMask.dll in the Plugins folder, since DepthMask can be installed separately

I noticed some issues on my side on the new version:
- The game looks like doesn't recognize the Forward Fuselage Module control as a valid control point, it always tells me "This vessel will be uncontrollable" even when having crew onboard, I need to add a probe core to the Orbiter first and then switch to the Fuselage control on the launch pad
- The NERVA engine has slightly angled thrust, so the Orbiter tends to pitch down
- I only get like 1400 m/s of Delta-V with the NERVA, seems too low to me, but I don't know

**Comment by rogerwang86** [comment]
Hi amoraschi
Creating a Discord is a great suggest, will add it into my plan.
Depth mask plugin issue is recognized, will solve it in the future.
And about your issue:

* It's a single case, I didn't heard same kind of thing before. Might need to check others mods you install. Or check the number and qualification of pilots , you need at least two qualified kerbals to fly the ship.
* Check your wings contain LOX or not, if it does, that mean you still using the old cfg file. Make sure remove all the SPOCK file in gamedate first, then install the new one. Also delete the ship save  entirely and build a new one. That might solve the problem.

**Comment by amoraschi** [comment]
Alright, that might be the issue, I only had one kerbal on the ship, thanks a lot for everything else too
